// AUTO-GENERATED by scripts/generate-locales.ts — DO NOT EDIT.
// Regenerate with: bun run locales:generate
import type { Translation } from './types';
import da from './locales/da/translation.json';
import de from './locales/de/translation.json';
import en from './locales/en/translation.json';
import es from './locales/es/translation.json';
import fr from './locales/fr/translation.json';
import hu from './locales/hu/translation.json';
import it from './locales/it/translation.json';
import nl from './locales/nl/translation.json';
import pl from './locales/pl/translation.json';
import pt from './locales/pt/translation.json';
import ru from './locales/ru/translation.json';
import sk from './locales/sk/translation.json';
import sr from './locales/sr/translation.json';
import tr from './locales/tr/translation.json';
import zh from './locales/zh/translation.json';

export type SupportedLanguage = 'da' | 'de' | 'en' | 'es' | 'fr' | 'hu' | 'it' | 'nl' | 'pl' | 'pt' | 'ru' | 'sk' | 'sr' | 'tr' | 'zh';

export const translations: Record<SupportedLanguage, Translation> = {
  da: da as Translation,
  de: de as Translation,
  en: en as Translation,
  es: es as Translation,
  fr: fr as Translation,
  hu: hu as Translation,
  it: it as Translation,
  nl: nl as Translation,
  pl: pl as Translation,
  pt: pt as Translation,
  ru: ru as Translation,
  sk: sk as Translation,
  sr: sr as Translation,
  tr: tr as Translation,
  zh: zh as Translation
};
