name: ðŸ› Bug Report
description: Report a bug or issue with Dynamic Weather Card
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Card Configuration
      description: Your card configuration (YAML)
      render: yaml
      placeholder: |
        type: custom:dynamic-weather-card
        entity: weather.home
        # ... your configuration
    validations:
      required: true

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant are you running?
      placeholder: e.g., 2024.1.0
    validations:
      required: true

  - type: input
    id: card-version
    attributes:
      label: Card Version
      description: What version of Dynamic Weather Card are you using?
      placeholder: e.g., 0.4.0
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      placeholder: e.g., Chrome 120, Firefox 121, Safari 17
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install the card?
      options:
        - HACS
        - Manual
    validations:
      required: true

  - type: textarea
    id: weather-integration
    attributes:
      label: Weather Integration
      description: Which weather integration are you using?
      placeholder: e.g., OpenWeatherMap, Met.no, AccuWeather, Yandex Weather, etc.
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: Browser Console Errors
      description: Any errors shown in the browser console? (F12 -> Console tab)
      render: shell
      placeholder: Paste console errors here

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any other information that might help

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have updated to the latest version of the card
          required: true
        - label: I have cleared my browser cache
          required: true
        - label: I have checked existing issues for duplicates
          required: true
        - label: I have included my card configuration
          required: true
